const mockCandidates = [
  {
    id: "cand-001",
    candidateCode: "C-2024-001",
    candidateName: "田中 太郎",
    candidateKana: "タナカ タロウ",
    jobName: "法人営業（東京）",
    companyName: "ABC株式会社",
    workLocation: "東京都港区",
    validApplication: true,
    phoneConnected: true,
    smsSent: true,
    advisorName: "佐藤アドバイザー",
    callerName: "山本オペレーター",
    phase: "初回面談設定",
    registeredDate: "2024-11-01",
    updatedAt: "2024-11-07T09:45:00",
    mediaRegisteredAt: "2024-10-29",
    source: "Indeed",
    phone: "090-1234-5678",
    email: "tanaka@example.com",
    birthday: "1991-02-14",
    age: 33,
    gender: "男性",
    education: "早稲田大学 商学部",
    postalCode: "105-0001",
    address: "東京都港区虎ノ門1-1-1",
    city: "港区",
    contactTime: "平日 10:00-19:00",
    remarks: "転居相談あり",
    memo: "初回面談予定調整中",
    smsConfirmed: true,
    firstContactPlannedAt: "2024-11-05",
    firstContactAt: "2024-11-06",
    attendanceConfirmed: true,
    callDate: "2024-11-03",
    scheduleConfirmedAt: "2024-11-04",
    resumeStatus: "提出済",
    recommendationDate: "2024-11-08",
    meetingVideoLink: "https://example.com/videos/tanaka",
    resumeForSend: "https://example.com/docs/tanaka_resume.pdf",
    workHistoryForSend: "https://example.com/docs/tanaka_history.pdf",
    partnerName: "高橋パートナー",
    introductionChance: "高い",
    newActionDate: "2024-11-10",
    actionInfo: { nextActionDate: "2024-11-18", finalResult: "----" },
    meetingPlans: [
      { sequence: 2, plannedDate: "2024-11-12", attendance: false },
      { sequence: 3, plannedDate: "", attendance: false },
    ],
    resumeDocuments: [{ label: "経歴書1", value: "Google Drive - 田中太郎" }],
    hearing: {
      relocation: "福岡への転居希望あり",
      desiredArea: "九州エリア（福岡市）",
      timing: "3ヶ月以内",
      desiredJob: "法人営業職",
      firstInterviewMemo: "オンラインで30分の面談を実施",
      currentIncome: "520万円",
      desiredIncome: "600万円",
      reason: "成長環境と裁量を求めて",
      interviewPreference: "平日夜 18時以降",
      recommendationText: "営業経験豊富でコミュニケーション力が高い",
      otherSelections: "2社で一次面接進行中",
      employmentStatus: "就業中",
    },
    selectionProgress: [
      {
        companyName: "ABC株式会社",
        route: "Indeed",
        recommendationDate: "2024-11-08",
        interviewSetupDate: "2024-11-09",
        interviewDate: "2024-11-12",
        offerDate: "",
        closingDate: "",
        acceptanceDate: "",
        onboardingDate: "",
        preJoinDeclineDate: "",
        fee: "30%",
        status: "一次面接予定",
        notes: "営業本部長との面接",
      },
    ],
    afterAcceptance: {
      amount: "1,200,000円",
      jobCategory: "営業",
      reportStatuses: ["LINE報告済み"],
    },
    refundInfo: { resignationDate: "", refundAmount: "", reportStatus: "" },
    csChecklist: {
      validConfirmed: true,
      connectConfirmed: true,
      dial1: true,
      dial2: true,
      dial3: false,
      dial4: false,
      dial5: false,
      dial6: false,
      dial7: false,
      dial8: false,
      dial9: false,
      dial10: false,
    },
    memoDetail: "初回面談で家族構成と転居スケジュールをヒアリング済み。",
  },
  {
    id: "cand-002",
    candidateCode: "C-2024-014",
    candidateName: "佐藤 花子",
    candidateKana: "サトウ ハナコ",
    jobName: "カスタマーサクセス",
    companyName: "XYZソリューションズ",
    workLocation: "大阪府大阪市",
    validApplication: true,
    phoneConnected: true,
    smsSent: false,
    advisorName: "中村アドバイザー",
    callerName: "上田オペレーター",
    phase: "一次面接調整",
    registeredDate: "2024-10-25",
    updatedAt: "2024-11-05T13:20:00",
    mediaRegisteredAt: "2024-10-18",
    source: "求人ボックス",
    phone: "080-2345-6789",
    email: "sato@example.com",
    birthday: "1995-07-03",
    gender: "女性",
    education: "神戸大学 経営学部",
    postalCode: "530-0001",
    address: "大阪府大阪市北区2-2-2",
    city: "大阪市北区",
    contactTime: "終日可（SMS希望）",
    remarks: "第二志望として別業界も検討中",
    memo: "一次面接日程調整中",
    smsConfirmed: false,
    firstContactPlannedAt: "2024-10-27",
    firstContactAt: "2024-10-28",
    attendanceConfirmed: false,
    callDate: "2024-10-26",
    scheduleConfirmedAt: "2024-10-30",
    resumeStatus: "未提出",
    recommendationDate: "2024-11-02",
    meetingVideoLink: "",
    resumeForSend: "",
    workHistoryForSend: "",
    partnerName: "佐々木パートナー",
    introductionChance: "中",
    actionInfo: { nextActionDate: "2024-11-15", finalResult: "----" },
    meetingPlans: [
      { sequence: 2, plannedDate: "2024-11-20", attendance: false },
    ],
    resumeDocuments: [],
    hearing: {
      relocation: "不可（大阪限定）",
      desiredArea: "大阪市内",
      timing: "半年以内",
      desiredJob: "CS・サポート職",
      firstInterviewMemo: "初回面談で志望動機を深掘り",
      currentIncome: "420万円",
      desiredIncome: "480万円",
      reason: "スキルを活かせる職場を希望",
      interviewPreference: "火木の午前",
      recommendationText: "サブスクビジネス経験者",
      otherSelections: "1社内定保留中",
      employmentStatus: "就業中",
    },
    selectionProgress: [
      {
        companyName: "XYZソリューションズ",
        route: "求人ボックス",
        recommendationDate: "2024-11-02",
        interviewSetupDate: "2024-11-05",
        interviewDate: "",
        offerDate: "",
        closingDate: "",
        acceptanceDate: "",
        onboardingDate: "",
        preJoinDeclineDate: "",
        fee: "25%",
        status: "一次面接日程調整",
        notes: "採用担当：小林様",
      },
    ],
    afterAcceptance: { amount: "", jobCategory: "", reportStatuses: [] },
    refundInfo: { resignationDate: "", refundAmount: "", reportStatus: "" },
    csChecklist: {
      validConfirmed: true,
      connectConfirmed: true,
      dial1: true,
      dial2: true,
      dial3: true,
      dial4: false,
      dial5: false,
      dial6: false,
      dial7: false,
      dial8: false,
      dial9: false,
      dial10: false,
    },
    memoDetail: "一次面接調整中。別求人との比較資料を送付予定。",
  },
  {
    id: "cand-003",
    candidateCode: "C-2024-025",
    candidateName: "山田 次郎",
    candidateKana: "ヤマダ ジロウ",
    jobName: "プロジェクトマネージャー",
    companyName: "TechForward株式会社",
    workLocation: "愛知県名古屋市",
    validApplication: true,
    phoneConnected: true,
    smsSent: true,
    advisorName: "石井アドバイザー",
    callerName: "田島オペレーター",
    phase: "内定承諾待ち",
    registeredDate: "2024-09-15",
    updatedAt: "2024-11-06T18:45:00",
    mediaRegisteredAt: "2024-09-10",
    source: "マイナビ",
    phone: "070-9876-5432",
    email: "yamada@example.com",
    birthday: "1988-11-20",
    gender: "男性",
    education: "名古屋工業大学 情報工学科",
    postalCode: "460-0008",
    address: "愛知県名古屋市中区3-3-3",
    city: "名古屋市中区",
    contactTime: "平日 9:00-18:00",
    remarks: "年収交渉中",
    memo: "内定承諾確認待ち",
    smsConfirmed: true,
    firstContactPlannedAt: "2024-09-18",
    firstContactAt: "2024-09-18",
    attendanceConfirmed: true,
    callDate: "2024-09-16",
    scheduleConfirmedAt: "2024-09-17",
    resumeStatus: "受領済",
    recommendationDate: "2024-09-19",
    meetingVideoLink: "https://example.com/videos/yamada",
    resumeForSend: "https://example.com/docs/yamada_resume.pdf",
    workHistoryForSend: "https://example.com/docs/yamada_history.pdf",
    partnerName: "川村パートナー",
    introductionChance: "非常に高い",
    actionInfo: { nextActionDate: "2024-11-11", finalResult: "承諾" },
    meetingPlans: [
      { sequence: 2, plannedDate: "2024-10-02", attendance: true },
    ],
    resumeDocuments: [
      { label: "経歴書1", value: "最新スキルシート2024" },
      { label: "経歴書2", value: "成果資料リンク" },
    ],
    hearing: {
      relocation: "可（条件付き）",
      desiredArea: "名古屋市内",
      timing: "即時",
      desiredJob: "IT系PM",
      firstInterviewMemo: "開発体制の課題を指摘",
      currentIncome: "780万円",
      desiredIncome: "850万円",
      reason: "さらなる裁量とリモート比率向上を希望",
      interviewPreference: "終日可（リモート）",
      recommendationText: "マネジメント経験豊富、英語対応可",
      otherSelections: "1社で最終面接待ち",
      employmentStatus: "離職中",
    },
    selectionProgress: [
      {
        companyName: "TechForward株式会社",
        route: "マイナビ",
        recommendationDate: "2024-09-19",
        interviewSetupDate: "2024-09-21",
        interviewDate: "2024-09-25",
        offerDate: "2024-10-05",
        closingDate: "2024-10-10",
        acceptanceDate: "",
        onboardingDate: "2024-12-01",
        preJoinDeclineDate: "",
        fee: "35%",
        status: "内定承諾待ち",
        notes: "年収交渉中",
      },
    ],
    afterAcceptance: {
      amount: "1,800,000円",
      jobCategory: "PM",
      reportStatuses: ["LINE報告済み", "個人シート反映済み"],
    },
    refundInfo: { resignationDate: "", refundAmount: "", reportStatus: "" },
    csChecklist: {
      validConfirmed: true,
      connectConfirmed: true,
      dial1: true,
      dial2: true,
      dial3: true,
      dial4: true,
      dial5: true,
      dial6: true,
      dial7: false,
      dial8: false,
      dial9: false,
      dial10: false,
    },
    memoDetail: "入社承諾連絡を11/11までに実施予定。",
  },
  {
    id: "cand-004",
    candidateCode: "C-2024-033",
    candidateName: "鈴木 未来",
    candidateKana: "スズキ ミライ",
    jobName: "UI/UXデザイナー",
    companyName: "CreativePlus",
    workLocation: "東京都渋谷区",
    validApplication: true,
    phoneConnected: false,
    smsSent: true,
    advisorName: "藤本アドバイザー",
    callerName: "森山オペレーター",
    phase: "入社準備",
    registeredDate: "2024-09-12",
    updatedAt: "2024-11-02T16:10:00",
    mediaRegisteredAt: "2024-09-01",
    source: "doda",
    phone: "050-3333-2222",
    email: "suzuki@example.com",
    birthday: "1993-05-11",
    gender: "女性",
    education: "千葉大学 デザイン学科",
    postalCode: "150-0002",
    address: "東京都渋谷区渋谷2-2-2",
    city: "渋谷区",
    contactTime: "平日 13:00-21:00",
    remarks: "リモート勤務希望",
    memo: "入社書類回収中",
    smsConfirmed: true,
    firstContactPlannedAt: "2024-09-14",
    firstContactAt: "2024-09-15",
    attendanceConfirmed: true,
    callDate: "2024-09-13",
    scheduleConfirmedAt: "2024-09-16",
    resumeStatus: "提出済",
    recommendationDate: "2024-09-18",
    meetingVideoLink: "",
    resumeForSend: "https://example.com/docs/suzuki_resume.pdf",
    workHistoryForSend: "https://example.com/docs/suzuki_history.pdf",
    partnerName: "森口パートナー",
    introductionChance: "高い",
    actionInfo: { nextActionDate: "2024-11-09", finalResult: "承諾" },
    meetingPlans: [],
    resumeDocuments: [{ label: "経歴書1", value: "Portfolio URL" }],
    hearing: {
      relocation: "不可（関東圏内）",
      desiredArea: "渋谷・新宿エリア",
      timing: "1ヶ月以内",
      desiredJob: "UI/UXデザイン",
      firstInterviewMemo: "ポートフォリオ説明に強み",
      currentIncome: "600万円",
      desiredIncome: "700万円",
      reason: "ミッションフィット",
      interviewPreference: "リモート面談希望",
      recommendationText: "Figmaスペシャリスト",
      otherSelections: "なし",
      employmentStatus: "就業中",
    },
    selectionProgress: [
      {
        companyName: "CreativePlus",
        route: "doda",
        recommendationDate: "2024-09-18",
        interviewSetupDate: "2024-09-22",
        interviewDate: "2024-09-25",
        offerDate: "2024-10-05",
        closingDate: "2024-10-15",
        acceptanceDate: "2024-10-20",
        onboardingDate: "2024-12-01",
        preJoinDeclineDate: "",
        fee: "28%",
        status: "入社準備中",
        notes: "在籍証明待ち",
      },
    ],
    afterAcceptance: {
      amount: "1,500,000円",
      jobCategory: "デザイナー",
      reportStatuses: [
        "LINE報告済み",
        "個人シート反映済み",
        "請求書送付済み",
      ],
    },
    refundInfo: { resignationDate: "", refundAmount: "", reportStatus: "" },
    csChecklist: {
      validConfirmed: true,
      connectConfirmed: false,
      dial1: true,
      dial2: true,
      dial3: true,
      dial4: true,
      dial5: true,
      dial6: true,
      dial7: true,
      dial8: true,
      dial9: false,
      dial10: false,
    },
    memoDetail: "入社書類の最終チェック中。",
  },
  {
    id: "cand-005",
    candidateCode: "C-2023-112",
    candidateName: "伊藤 圭介",
    candidateKana: "イトウ ケイスケ",
    jobName: "バックオフィス責任者",
    companyName: "NextStage株式会社",
    workLocation: "神奈川県横浜市",
    validApplication: false,
    phoneConnected: false,
    smsSent: false,
    advisorName: "大谷アドバイザー",
    callerName: "今井オペレーター",
    phase: "クローズ",
    registeredDate: "2023-12-05",
    updatedAt: "2024-01-10T10:15:00",
    mediaRegisteredAt: "2023-12-01",
    source: "リクナビ",
    phone: "090-7777-8888",
    email: "ito@example.com",
    birthday: "1985-04-30",
    gender: "男性",
    education: "中央大学 経済学部",
    postalCode: "220-0001",
    address: "神奈川県横浜市西区1-1-1",
    city: "横浜市西区",
    contactTime: "午前中のみ",
    remarks: "家庭の事情で転職停止",
    memo: "転職活動停止のためクローズ",
    smsConfirmed: false,
    firstContactPlannedAt: "2023-12-06",
    firstContactAt: "",
    attendanceConfirmed: false,
    callDate: "2023-12-06",
    scheduleConfirmedAt: "",
    resumeStatus: "未提出",
    recommendationDate: "",
    meetingVideoLink: "",
    resumeForSend: "",
    workHistoryForSend: "",
    partnerName: "該当なし",
    introductionChance: "低い",
    actionInfo: { nextActionDate: "", finalResult: "リリース(転居不可)" },
    meetingPlans: [],
    resumeDocuments: [],
    hearing: {
      relocation: "不可",
      desiredArea: "横浜市内のみ",
      timing: "未定",
      desiredJob: "管理部門",
      firstInterviewMemo: "初回面談前に離脱",
      currentIncome: "680万円",
      desiredIncome: "700万円",
      reason: "ワークライフバランス改善",
      interviewPreference: "",
      recommendationText: "リファレンス良好",
      otherSelections: "なし",
      employmentStatus: "就業中",
    },
    selectionProgress: [],
    afterAcceptance: { amount: "", jobCategory: "", reportStatuses: [] },
    refundInfo: { resignationDate: "", refundAmount: "", reportStatus: "" },
    csChecklist: {
      validConfirmed: false,
      connectConfirmed: false,
      dial1: true,
      dial2: true,
      dial3: false,
      dial4: false,
      dial5: false,
      dial6: false,
      dial7: false,
      dial8: false,
      dial9: false,
      dial10: false,
    },
    memoDetail: "家庭の事情で無期限延期。",
  },
];

module.exports = mockCandidates;
